-- Auto-generated by `npm run dump` — full schema + seed data.
-- Import via phpMyAdmin (Import tab) or: mysql -u <user> -p <db> < dump.sql

-- Navyrix Labs / dipen-bhai portfolio — MySQL schema
-- Run once against a fresh database: mysql -u <user> -p <db> < schema.sql

CREATE TABLE IF NOT EXISTS admin_users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);

-- Singleton row (id always 1): personal/company profile shown across the site
CREATE TABLE IF NOT EXISTS profile (
  id INT PRIMARY KEY,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  full_name VARCHAR(200),
  tagline VARCHAR(500),
  role_description VARCHAR(500),
  short_bio TEXT,
  about_headline VARCHAR(500),
  about_intro TEXT,
  avatar_url VARCHAR(500),
  cv_url VARCHAR(500),
  cta_discovery_url VARCHAR(500),
  trust_stats JSON,   -- [{id, value, label}]
  trust_brands JSON   -- ["Qualcomm", ...]
);

-- Singleton row (id always 1): SEO + contact details
CREATE TABLE IF NOT EXISTS settings (
  id INT PRIMARY KEY,
  seo_title VARCHAR(255),
  seo_description VARCHAR(1000),
  seo_keywords VARCHAR(1000),
  contact_email VARCHAR(255),
  contact_phone VARCHAR(50),
  contact_linkedin VARCHAR(255),
  contact_location VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS ventures (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  name VARCHAR(255),
  description TEXT,
  status VARCHAR(255),
  website VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS expertise (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  number VARCHAR(10),
  title VARCHAR(255),
  description TEXT,
  skills JSON -- ["skill1", "skill2", ...]
);

-- Singleton row (id always 1)
CREATE TABLE IF NOT EXISTS ecosystem (
  id INT PRIMARY KEY,
  headline VARCHAR(255),
  subheading TEXT
);

CREATE TABLE IF NOT EXISTS ecosystem_activities (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  title VARCHAR(255),
  detail TEXT
);

CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  number VARCHAR(10),
  title VARCHAR(255),
  category VARCHAR(255),
  image VARCHAR(500),
  short_description TEXT,
  challenge TEXT,
  solution TEXT,
  outcome TEXT,
  technologies JSON,
  role VARCHAR(255),
  url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS journey (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  year VARCHAR(50),
  company VARCHAR(255),
  role VARCHAR(255),
  description TEXT
);

CREATE TABLE IF NOT EXISTS speaking (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  date VARCHAR(50),
  event VARCHAR(255),
  topic VARCHAR(255),
  description TEXT,
  image VARCHAR(500)
);

-- Separate public Talks page content; independent from portfolio speaking entries.
CREATE TABLE IF NOT EXISTS talks (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  date VARCHAR(50),
  event VARCHAR(255),
  topic VARCHAR(255),
  image VARCHAR(500)
);

-- Singleton row (id always 1)
CREATE TABLE IF NOT EXISTS global_presence (
  id INT PRIMARY KEY,
  headline VARCHAR(255),
  description TEXT,
  countries JSON
);

CREATE TABLE IF NOT EXISTS skills (
  id INT PRIMARY KEY AUTO_INCREMENT,
  sort_order INT DEFAULT 0,
  skill VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS certifications (
  id VARCHAR(50) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  title VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS process_steps (
  step VARCHAR(10) PRIMARY KEY,
  sort_order INT DEFAULT 0,
  name VARCHAR(100),
  description TEXT
);

-- Consolidates the 7 credential sub-lists (technical/mentor projects, jury
-- slots, lectures, patents, copyrights, memberships) into one flexible table.
CREATE TABLE IF NOT EXISTS credentials (
  id INT PRIMARY KEY AUTO_INCREMENT,
  category ENUM(
    'technical_project', 'mentor_project', 'jury_slot',
    'lecture', 'patent', 'copyright', 'membership'
  ) NOT NULL,
  sort_order INT DEFAULT 0,
  content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS leads (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  company VARCHAR(255),
  industry VARCHAR(255),
  description TEXT,
  budget VARCHAR(100),
  timeline VARCHAR(100),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blogs (
  id VARCHAR(50) PRIMARY KEY,
  title VARCHAR(500),
  slug VARCHAR(500) UNIQUE,
  excerpt TEXT,
  content LONGTEXT,
  image VARCHAR(500),
  category VARCHAR(255),
  read_time VARCHAR(50),
  published_date VARCHAR(100),
  published BOOLEAN DEFAULT TRUE,
  sort_order INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- ---- seed data ----

-- admin login
INSERT INTO `admin_users` (`username`, `password_hash`) VALUES ('admin', '$2a$12$Dn9kRCGUIkRZkVEoP874I.dUZ5yGBdv73ZebibEIR6IDK5KU77jU2');

-- profile (singleton)
INSERT INTO `profile` (`id`, `first_name`, `last_name`, `full_name`, `tagline`, `role_description`, `short_bio`, `about_headline`, `about_intro`, `avatar_url`, `cv_url`, `cta_discovery_url`, `trust_stats`, `trust_brands`) VALUES (1, 'NAVYRIX', 'LABS', 'NAVYRIX LABS', 'Engineering Ideas Into Products That Ship.', 'Product Engineering Services (Electronics & Defense, Agritech, Biotech) | IoT & Connected Systems | Agile Product Architecture | Startup Mentor & Consulting Services | Expert Talks', 'NAVYRIX is a product engineering practice led by Dipen Parmar, built on 18+ years across electronics, defense, agritech, and biotech. We take connected ideas from first sketch to certified, mass production — and mentor the founders building the next generation of innovative hardware startups..', 'Two decades of engineering discipline. One partner for product execution.', 'At Navyrix Labs, we combine 18+ years of embedded systems expertise with startup product delivery, agritech innovation, and technology mentorship. Led by Chief Architect Dipen Parmar, our specialized engineering group helps organizations design, validate, and scale connected hardware systems.', '/dipen_hero.png', '#', 'https://calendly.com/dipen-parmar/30min', '[{\"id\":\"stat-1\",\"value\":\"18+\",\"label\":\"Years Experience\"},{\"id\":\"stat-2\",\"value\":\"12+\",\"label\":\"Years SLS Leadership\"},{\"id\":\"stat-3\",\"value\":\"2+\",\"label\":\"Years at Qualcomm\"},{\"id\":\"stat-4\",\"value\":\"5+\",\"label\":\"Animal Husbandry & Agritech\"},{\"id\":\"stat-5\",\"value\":\"20+\",\"label\":\"Tech & Startup Talks\"},{\"id\":\"stat-6\",\"value\":\"30+\",\"label\":\"Startup Mentorship\"}]', '[\"Qualcomm\",\"System Level Solutions\",\"Nebulae IoT\",\"ME2MILLET\",\"LibreRouter\",\"i-Hub Gujarat\"]');

-- settings (singleton)
INSERT INTO `settings` (`id`, `seo_title`, `seo_description`, `seo_keywords`, `contact_email`, `contact_phone`, `contact_linkedin`, `contact_location`) VALUES (1, 'Navyrix Labs | Embedded Systems, IoT & Product Engineering Services', 'Navyrix Labs delivers embedded systems, IoT architecture, and end-to-end product engineering — from firmware and connected hardware to certification and mass production — across electronics, defense, agritech, and biotech.', 'embedded systems, IoT architecture, product engineering services, firmware development, connected hardware design, agritech IoT, defense electronics, startup mentorship, hardware prototyping, mass manufacturing support', 'info@navyrix.com', '+91 99987 44676', 'linkedin.com/in/dipenparmar', 'Gujarat, India');

-- ventures
INSERT INTO `ventures` (`id`, `sort_order`, `name`, `description`, `status`, `website`) VALUES ('v-1', 0, 'ME2MILLET', 'A brand of Krishitattva Agtech Private Limited. Focused on millet awareness, farming, and processing, and on value-added gluten-free products in Ready-to-Cook and Ready-to-Eat categories.', 'Co-Founder', 'www.me2millet.com | www.krishitattva.com');
INSERT INTO `ventures` (`id`, `sort_order`, `name`, `description`, `status`, `website`) VALUES ('v-2', 1, 'Gavyam Gentech Private Limited', 'Animal husbandry (agritech and biotech) IoT products and services for animal breeding and monitoring.', 'Past: Director & Technology Architect | Past Co-Founder', 'www.gavyamgentec.com');
INSERT INTO `ventures` (`id`, `sort_order`, `name`, `description`, `status`, `website`) VALUES ('v-3', 2, 'Defen System Solutions Private Limited', 'Defense electronics product development.', 'Past: Director | Past Co-Founder', '');
INSERT INTO `ventures` (`id`, `sort_order`, `name`, `description`, `status`, `website`) VALUES ('v-4', 3, 'System Level Solutions Private Limited', 'Custom embedded products and services, and IoT architecture including gateway and other subsystems.', 'Past: Sr. Manager', 'www.slscorp.com');

-- expertise
INSERT INTO `expertise` (`id`, `sort_order`, `number`, `title`, `description`, `skills`) VALUES ('exp-1', 0, '01', 'Embedded Systems', 'Custom embedded product development that includes sensor, gateway, cloud, and application layers — web and mobile based.', '[\"Embedded Architecture\",\"(Secure) Linux/RTOS and FoTA\",\"Protocol and Cloud Agnostic Connectivity\"]');
INSERT INTO `expertise` (`id`, `sort_order`, `number`, `title`, `description`, `skills`) VALUES ('exp-2', 1, '02', 'IoT & Connected Products', 'End-to-end communication network architectures and industrial networking protocols.', '[\"Smart City\",\"Sensor Networks\",\"Zigbee\",\"Wi-Fi\",\"BLE\",\"LoRa\",\"Wired Network\",\"Modbus\",\"MQTT\",\"NB-IoT\"]');
INSERT INTO `expertise` (`id`, `sort_order`, `number`, `title`, `description`, `skills`) VALUES ('exp-3', 2, '03', 'Product Engineering', 'Guiding hardware concepts from specifications to market-ready architecture.', '[\"Architecture Design\",\"Prototype Development\",\"Regulatory Testing\",\"Field Pilot Runs\",\"Production Readiness\",\"Patent, Copyrights Generation and Review, Open Source Compliances\"]');
INSERT INTO `expertise` (`id`, `sort_order`, `number`, `title`, `description`, `skills`) VALUES ('exp-4', 3, '04', 'AI + IoT', 'Edge intelligence and data-driven connected hardware.', '[\"Sensor Intelligence\",\"AI/ML Integration\",\"Connected Agriculture\",\"Data-driven Products\"]');
INSERT INTO `expertise` (`id`, `sort_order`, `number`, `title`, `description`, `skills`) VALUES ('exp-5', 4, '05', 'Manufacturing', 'Bridge between PoC (Proof of Concept) and mass manufacturing, with automation test support and certification services including user manual and packaging needs.', '[\"Product Readiness\",\"Certification Support\",\"Quality Systems\",\"Production Support\"]');

-- ecosystem (singleton) + activities
INSERT INTO `ecosystem` (`id`, `headline`, `subheading`) VALUES (1, 'Beyond Engineering.', 'Building technology is only one part of the journey. Navyrix Labs actively mentors, evaluates, and contributes to scaling connected product ecosystems.');

INSERT INTO `ecosystem_activities` (`id`, `sort_order`, `title`, `detail`) VALUES ('act-1', 0, 'STARTUP MENTOR & JURY', 'Agritech Mentor & Jury member at Sardar Patel Startup Entrepreneurship Council and i-Hub Gujarat (past), guiding early-stage innovators.');
INSERT INTO `ecosystem_activities` (`id`, `sort_order`, `title`, `detail`) VALUES ('act-2', 1, 'AGRITECH INNOVATOR', 'Co-founder of Krishitattva (ME2MILLET). Past: Gavyam Gentech, deploying IoT and AI/ML systems in animal husbandry and sustainable farming.');
INSERT INTO `ecosystem_activities` (`id`, `sort_order`, `title`, `detail`) VALUES ('act-3', 2, 'OPEN-SOURCE CONTRIBUTOR', 'Active contributor to open-source hardware and software products, including LibreRouter — developed for community network needs.');
INSERT INTO `ecosystem_activities` (`id`, `sort_order`, `title`, `detail`) VALUES ('act-4', 3, 'INDUSTRY SPEAKER', 'Expert Speaker at AICTE ATAL Academy FDP programs, engineering colleges, and startup incubator workshops.');

-- projects (empty - "coming soon")
-- (no rows for projects)

-- journey (empty - removed per content review)
-- (no rows for journey)

-- speaking
INSERT INTO `speaking` (`id`, `sort_order`, `date`, `event`, `topic`) VALUES ('sp-1', 0, 'Dec 2024', 'AICTE ATAL Academy FDP', 'Next-Gen IoT and Edge Intelligence in Agriculture');
INSERT INTO `speaking` (`id`, `sort_order`, `date`, `event`, `topic`) VALUES ('sp-2', 1, 'Oct 2024', 'i-Hub Gujarat Startup Incubator', 'Hardware Prototyping: From Schematic to Mass Production');
INSERT INTO `speaking` (`id`, `sort_order`, `date`, `event`, `topic`) VALUES ('sp-3', 2, 'Jul 2024', 'Sardar Patel SEC Seminar', 'Bridging the Gap: IoT Product-Market Fit for Agritech Founders');
INSERT INTO `speaking` (`id`, `sort_order`, `date`, `event`, `topic`) VALUES ('sp-4', 3, 'Feb 2024', 'SVIT Engineering College Lecture', 'Career Pathways in Modern Embedded Linux & Wireless Networking');

-- global_presence (singleton)
INSERT INTO `global_presence` (`id`, `headline`, `description`, `countries`) VALUES (1, 'Technology Without Borders.', 'International business exposure, global client support, and technical trade representation across crucial tech hubs.', '[\"United Kingdom\",\"Japan\",\"China\",\"European Union\",\"Oman\",\"United Arab Emirates\"]');

-- skills
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (0, 'C');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (1, 'C++');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (2, 'Python');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (3, 'Linux Kernel');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (4, 'FreeRTOS');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (5, 'U-Boot');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (6, '8/32/64-bit ARM');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (7, 'RISC');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (8, 'FPGA Processors');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (9, 'STM32');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (10, 'IoT');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (11, '6LoWPAN');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (12, 'Zigbee');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (13, 'Wi-Fi');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (14, 'PCIe');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (15, 'I2C');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (16, 'SPI');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (17, 'UART');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (18, 'Git');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (19, 'GitHub');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (20, 'GitLab');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (21, 'Gerrit');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (22, 'Jenkins');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (23, 'Jira');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (24, 'Tuleap');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (25, 'MISRA C');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (26, 'FoTA');
INSERT INTO `skills` (`sort_order`, `skill`) VALUES (27, 'Unity C');

-- certifications
INSERT INTO `certifications` (`id`, `sort_order`, `title`) VALUES ('c-1', 0, 'Certified Scrum Product Owner (CSPO)');
INSERT INTO `certifications` (`id`, `sort_order`, `title`) VALUES ('c-2', 1, 'ISO 9001 Quality Management Systems Internal Auditor');
INSERT INTO `certifications` (`id`, `sort_order`, `title`) VALUES ('c-3', 2, 'ISO 27001 Information Security Management Systems Internal Auditor');
INSERT INTO `certifications` (`id`, `sort_order`, `title`) VALUES ('c-4', 3, 'ISO 13485 Medical Devices QMS Knowledge');
INSERT INTO `certifications` (`id`, `sort_order`, `title`) VALUES ('c-5', 4, 'MISRA C Programming Standard Expert');

-- process_steps
INSERT INTO `process_steps` (`step`, `sort_order`, `name`, `description`) VALUES ('01', 0, 'Discovery', 'Understanding the problem, feasibility analysis, and defining product requirements.');
INSERT INTO `process_steps` (`step`, `sort_order`, `name`, `description`) VALUES ('02', 1, 'Architecture', 'Defining product architecture — hardware schematics, software stack, low-power constraints, and connectivity protocols — considering stability, cost, and user adaptability.');
INSERT INTO `process_steps` (`step`, `sort_order`, `name`, `description`) VALUES ('03', 2, 'Prototype', 'Quick PoC with off-the-shelf development kits, or spinning initial PCB runs and developing first-stage firmware for lab testing.');
INSERT INTO `process_steps` (`step`, `sort_order`, `name`, `description`) VALUES ('04', 3, 'Testing', 'Rigorous testing of board interfaces, range coverage, power profiles, and code reliability.');
INSERT INTO `process_steps` (`step`, `sort_order`, `name`, `description`) VALUES ('05', 4, 'Pilot', 'Deploying a small batch of hardware units in real-world field environments to collect telemetry.');
INSERT INTO `process_steps` (`step`, `sort_order`, `name`, `description`) VALUES ('06', 5, 'Production', 'Sourcing components, designing test jigs, and finalizing QA systems for volume assembly.');
INSERT INTO `process_steps` (`step`, `sort_order`, `name`, `description`) VALUES ('07', 6, 'Support', 'Rolling out secure FOTA updates and maintaining field hardware throughout its life cycle, including product after-life support for repair and bug fixes.');

-- credentials (consolidated categories)
INSERT INTO `credentials` (`category`, `sort_order`, `content`) VALUES ('jury_slot', 0, 'Past: Startup Pitch Evaluator & Jury Panelist, i-Hub Gujarat');
INSERT INTO `credentials` (`category`, `sort_order`, `content`) VALUES ('jury_slot', 1, 'Past: Startup Pitch Evaluator & Jury Panelist, Sardar Patel Startup and Entrepreneurship Council, Anand');
INSERT INTO `credentials` (`category`, `sort_order`, `content`) VALUES ('patent', 0, 'Paper Submitted: Dual-bank secure OTA firmware updating method for low-power mesh utility nodes (details to follow)');

-- leads (sample enquiries)
INSERT INTO `leads` (`id`, `name`, `email`, `company`, `industry`, `description`, `budget`, `timeline`, `created_at`) VALUES ('lead-1', 'Rajesh Patel', 'rpatel@agrotech-ventures.in', 'Agrotech Ventures Ltd', 'Agritech', 'Looking to develop a solar-powered soil moisture node network using LoRaWAN mesh communication. Need guidance on hardware design and production prep.', '10,000 - 25,000 USD', '3 - 6 Months', '2026-08-09 20:02:00.000');
INSERT INTO `leads` (`id`, `name`, `email`, `company`, `industry`, `description`, `budget`, `timeline`, `created_at`) VALUES ('lead-2', 'Kenji Tanaka', 't.kenji@smart-grid-jp.com', 'Tokyo Grid Analytics', 'Energy / Utilities', 'Need help reviewing firmware security standards and G3-PLC/DLMS integration for utility gateway endpoints.', '25,000+ USD', '1 - 3 Months', '2026-08-10 14:45:00.000');

-- blogs
INSERT INTO `blogs` (`id`, `title`, `slug`, `excerpt`, `content`, `image`, `category`, `read_time`, `published_date`, `published`, `sort_order`) VALUES ('blog-1', 'The Future of Agritech: IoT Sensors in Millet Farming', 'future-of-agritech-millet-farming', 'Exploring how soil moisture, ambient humidity, and NPK metrics collected via sub-GHz low power nodes can optimize crop yields and save water resources in arid regions.', 'The intersection of electronics and agriculture holds the key to solving global food security challenges. In recent years, millet farming—particularly in dry regions of India and sub-Saharan Africa—has benefited immensely from targeted IoT deployments.\n\n### Why Millets?\nMillets are highly resilient crops, but they are extremely sensitive to waterlogging and nutrient depletion during early vegetative phases. Traditional agricultural methods rely on guesswork, which often leads to over-watering or soil salinity issues.\n\n### The Role of IoT Nodes\nBy deploying sub-GHz wireless sensor nodes equipped with soil moisture probes, temperature sensors, and electrical conductivity sensors, we can feed real-time analytics to dashboard systems.\n\n1. **Sub-GHz Mesh Networks**: Sub-GHz radio frequencies (like 868MHz or 915MHz) provide excellent propagation through dense foliage, allowing nodes to communicate across vast crop fields.\n2. **Ultra-Low Power Harvesting**: Deploying nodes that run on tiny solar cells combined with supercapacitors ensures zero-maintenance lifecycles of up to 5-10 years.\n3. **Edge Inferences**: Filtering raw telemetry data at the node level before transmission reduces radio power consumption, which is the largest drain on battery systems.\n\nAt **ME2MILLET**, our mission has been to commoditize these edge sensor networks, proving that smart hardware can create measurable ecological and commercial benefits for local growers.', '/me2millet.png', 'Agritech', '4 min read', 'August 10, 2026', 1, 0);
