// Generates server/dump.sql: the full schema plus all seed data, as a single
// plain-SQL file with no live DB connection required. Import it via
// Hostinger's phpMyAdmin ("Import" tab) or `mysql -u user -p dbname < dump.sql`.
//
// Usage: npm run dump   (reads server/.env for the admin password to hash)

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const mysql = require('mysql2');
const {
  profile, settings, ventures, expertise, ecosystem, ecosystemActivities,
  projects, speaking, talks, globalPresence, skills, certifications,
  processSteps, credentials, leads, blogs,
} = require('./seedData');

function insertSql(table, columns, rows) {
  if (!rows.length) return `-- (no rows for ${table})\n`;
  const placeholders = `(${columns.map(() => '?').join(', ')})`;
  return rows
    .map((row) => mysql.format(`INSERT INTO \`${table}\` (${columns.map((c) => `\`${c}\``).join(', ')}) VALUES ${placeholders};`, row))
    .join('\n') + '\n';
}

async function main() {
  const username = process.env.INITIAL_ADMIN_USERNAME || 'admin';
  const password = process.env.INITIAL_ADMIN_PASSWORD;
  if (!password) throw new Error('INITIAL_ADMIN_PASSWORD is not set in server/.env');
  const passwordHash = await bcrypt.hash(password, 12);

  const schema = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');

  const parts = [];
  parts.push('-- Auto-generated by `npm run dump` — full schema + seed data.');
  parts.push('-- Import via phpMyAdmin (Import tab) or: mysql -u <user> -p <db> < dump.sql');
  parts.push('');
  parts.push(schema);
  parts.push('');
  parts.push('-- ---- seed data ----');
  parts.push('');

  parts.push('-- admin login');
  parts.push(insertSql('admin_users', ['username', 'password_hash'], [[username, passwordHash]]));

  parts.push('-- profile (singleton)');
  parts.push(insertSql('profile', [
    'id', 'first_name', 'last_name', 'full_name', 'tagline', 'role_description', 'short_bio',
    'about_headline', 'about_intro', 'avatar_url', 'cv_url', 'cta_discovery_url', 'trust_stats', 'trust_brands',
  ], [[
    1, profile.firstName, profile.lastName, profile.fullName, profile.tagline, profile.roleDescription, profile.shortBio,
    profile.aboutHeadline, profile.aboutIntro, profile.avatarUrl, profile.cvUrl, profile.ctaDiscoveryUrl,
    JSON.stringify(profile.trustStats), JSON.stringify(profile.trustBrands),
  ]]));

  parts.push('-- settings (singleton)');
  parts.push(insertSql('settings', [
    'id', 'seo_title', 'seo_description', 'seo_keywords', 'contact_email', 'contact_phone', 'contact_linkedin', 'contact_location',
  ], [[
    1, settings.seoTitle, settings.seoDescription, settings.seoKeywords,
    settings.contactEmail, settings.contactPhone, settings.contactLinkedin, settings.contactLocation,
  ]]));

  parts.push('-- ventures');
  parts.push(insertSql('ventures', ['id', 'sort_order', 'name', 'description', 'status', 'website'],
    ventures.map((v, i) => [v.id, i, v.name, v.desc, v.status, v.website])));

  parts.push('-- expertise');
  parts.push(insertSql('expertise', ['id', 'sort_order', 'number', 'title', 'description', 'skills'],
    expertise.map((x, i) => [x.id, i, x.number, x.title, x.description, JSON.stringify(x.skills)])));

  parts.push('-- ecosystem (singleton) + activities');
  parts.push(insertSql('ecosystem', ['id', 'headline', 'subheading'], [[1, ecosystem.headline, ecosystem.subheading]]));
  parts.push(insertSql('ecosystem_activities', ['id', 'sort_order', 'title', 'detail'],
    ecosystemActivities.map((a, i) => [a.id, i, a.title, a.detail])));

  parts.push('-- projects (empty - "coming soon")');
  parts.push(insertSql('projects', [
    'id', 'sort_order', 'number', 'title', 'category', 'image', 'short_description', 'challenge', 'solution', 'outcome', 'technologies', 'role', 'url',
  ], projects.map((p, i) => [
    p.id, i, p.number, p.title, p.category, p.image, p.shortDescription, p.challenge, p.solution, p.outcome,
    JSON.stringify(p.technologies || []), p.role, p.url,
  ])));

  parts.push('-- journey (empty - removed per content review)');
  parts.push('-- (no rows for journey)\n');

  parts.push('-- speaking');
  parts.push(insertSql('speaking', ['id', 'sort_order', 'date', 'event', 'topic'],
    speaking.map((s, i) => [s.id, i, s.date, s.event, s.topic])));

  parts.push('-- independent Talks page content');
  parts.push(insertSql('talks', ['id', 'sort_order', 'date', 'event', 'topic', 'image'],
    talks.map((talk, i) => [talk.id, i, talk.date, talk.event, talk.topic, talk.image || ''])));

  parts.push('-- global_presence (singleton)');
  parts.push(insertSql('global_presence', ['id', 'headline', 'description', 'countries'],
    [[1, globalPresence.headline, globalPresence.description, JSON.stringify(globalPresence.countries)]]));

  parts.push('-- skills');
  parts.push(insertSql('skills', ['sort_order', 'skill'], skills.map((s, i) => [i, s])));

  parts.push('-- certifications');
  parts.push(insertSql('certifications', ['id', 'sort_order', 'title'],
    certifications.map((c, i) => [c.id, i, c.title])));

  parts.push('-- process_steps');
  parts.push(insertSql('process_steps', ['step', 'sort_order', 'name', 'description'],
    processSteps.map((p, i) => [p.step, i, p.name, p.desc])));

  parts.push('-- credentials (consolidated categories)');
  const credentialRows = [];
  for (const [category, items] of Object.entries(credentials)) {
    items.forEach((content, i) => credentialRows.push([category, i, content]));
  }
  parts.push(insertSql('credentials', ['category', 'sort_order', 'content'], credentialRows));

  parts.push('-- leads (sample enquiries)');
  parts.push(insertSql('leads', ['id', 'name', 'email', 'company', 'industry', 'description', 'budget', 'timeline', 'created_at'],
    leads.map((l) => [l.id, l.name, l.email, l.company, l.industry, l.description, l.budget, l.timeline, new Date(l.createdAt)])));

  parts.push('-- blogs');
  parts.push(insertSql('blogs', ['id', 'title', 'slug', 'excerpt', 'content', 'image', 'category', 'read_time', 'published_date', 'published', 'sort_order'],
    blogs.map((b, i) => [b.id, b.title, b.slug, b.excerpt, b.content, b.image, b.category, b.readTime, b.publishedDate, b.published ? 1 : 0, i])));

  const outPath = path.join(__dirname, '..', 'dump.sql');
  fs.writeFileSync(outPath, parts.join('\n'));
  console.log(`Wrote ${outPath}`);
  console.log(`Admin login once imported: username="${username}", password=<what's in INITIAL_ADMIN_PASSWORD> — change it after first login.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
